"""ComplexWorker: for architecture design and complex tasks.

Strategy: Load full project context, design documents, and all relevant files.
"""

from __future__ import annotations

from typing import Any

from .base import BaseWorker, WorkerContext
from ..task_spec import TaskSpec
from ..orchestrator import ExecutionResult


class ComplexWorker(BaseWorker):
    """Worker for complex architecture tasks.

    - Cross-module changes
    - Architecture decisions
    - Requires full project context
    """

    worker_type = "complex"

    async def execute(self, task: TaskSpec, context: WorkerContext) -> ExecutionResult:
        """Execute a complex task."""
        prompt = self._build_prompt(task, context)

        # Add full project context
        if context.project_context:
            prompt += "\n\n[项目上下文]\n"
            for key, value in context.project_context.items():
                prompt += f"  {key}: {value}\n"

        # Add all related files
        if context.related_files:
            prompt += "\n[相关文件列表]\n"
            for f in context.related_files:
                prompt += f"  - {f}\n"

        outputs = {}
        for output_path in task.outputs:
            outputs[output_path] = f"# Generated by ComplexWorker for {task.id}\n"

        return ExecutionResult(
            task_id=task.id,
            success=True,
            output={"prompt": prompt, "outputs": outputs},
            artifacts=outputs,
            token_usage=len(prompt) // 4,
        )
