"""SimpleWorker: for single-file modifications (<50 lines).

Strategy: Load only the target file, make minimal changes.
"""

from __future__ import annotations

from typing import Any

from .base import BaseWorker, WorkerContext
from ..task_spec import TaskSpec
from ..orchestrator import ExecutionResult


class SimpleWorker(BaseWorker):
    """Worker for very simple tasks.

    - Single file changes
    - < 50 lines modified
    - No complex dependencies
    """

    worker_type = "simple"

    async def execute(self, task: TaskSpec, context: WorkerContext) -> ExecutionResult:
        """Execute a simple task.

        For now, this is a placeholder that simulates execution.
        In production, this would call the actual LLM with a focused prompt.
        """
        # Build focused prompt
        prompt = self._build_prompt(task, context)

        # Simulate execution
        # In production: call LLM with prompt, parse structured output
        outputs = {}
        for output_path in task.outputs:
            outputs[output_path] = (
                f"# Generated by SimpleWorker for {task.id}\n# {task.objective}\n"
            )

        return ExecutionResult(
            task_id=task.id,
            success=True,
            output={"prompt": prompt, "outputs": outputs},
            artifacts=outputs,
            token_usage=len(prompt) // 4,
        )
