"""StandardWorker: for module-level development.

Strategy: Load target file + related interfaces + dependencies.
"""

from __future__ import annotations


from .base import BaseWorker, WorkerContext
from ..task_spec import TaskSpec
from ..results import ExecutionResult


class StandardWorker(BaseWorker):
    """Worker for standard module-level tasks.

    - Multi-file changes within a module
    - Requires understanding of interfaces
    - May need to read related files
    """

    worker_type = "standard"

    async def execute(self, task: TaskSpec, context: WorkerContext) -> ExecutionResult:
        """Execute a standard task."""
        prompt = self._build_prompt(task, context)

        # Add related files context
        if context.related_files:
            prompt += "\n\n[相关文件]\n"
            for f in context.related_files[:5]:
                prompt += f"  - {f}\n"

        outputs = {}
        for output_path in task.outputs:
            outputs[output_path] = f"# Generated by StandardWorker for {task.id}\n"

        return ExecutionResult(
            task_id=task.id,
            success=True,
            output={"prompt": prompt, "outputs": outputs},
            artifacts=outputs,
            token_usage=len(prompt) // 4,
        )
